### ISSUE TITLE
Install Git-LFS in docker feelpp/feelpp-env

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/docker#14]
git lfs is not installed in the docker image.
I see that because the mesh  ```feelpp/toolboxes/thermoelectric/ElectroMagnets/HL-31_H1/HL-31_H1-coarse.msh ```  is not downloaded (not present in docker image) and thus this example doesn't work.

Maybe, we move soon this mesh in girder (when url download will be available in Feel).
Hower it maybe usefull to have git lfs in the docker image.

@prudhomm what do you think?

**Comment by prudhomm** [comment]
@vincentchabannes I pushed the fix. There are a few other things as well such as copying the testcase in /feel so that the user can play with them in a read-write environment.

**Comment by prudhomm** [comment]
The new docker feelpp/feelpp-env is already in place with git-lfs

**Comment by vincentchabannes** [comment]
:+1:

**Comment by vincentchabannes** [comment]
about copying testcases in /feel, it's do at each run? why not just define a environment variable, in order to have the same behavior docker vs singularity.

**Comment by prudhomm** [comment]
I would guess it is the issue @lotfi is facing right ?

**Comment by prudhomm** [comment]
@vincentchabannes regarding moving the mesh to girder, I agree! this is now our policy
