### ISSUE TITLE
v.105 alpha tag incorrect

### ISSUE THREAD

**Issue by gdolle** [feelpp/docker#16]
The dockerhub tag for the version 105 alpha currently does not respect the tag naming convention due to a typo. This breaks singularity pipeline latest tag conversion.

Current:
`develop-v0.105.0alpha.1-ubuntu-16.04`

Should be:
`develop-v0.105.0-alpha.1-ubuntu-16.04`

**Comment by prudhomm** [comment]
why does it break the singularity build? I just forgot to put a `-` before `alpha`. it is just a version name

**Comment by prudhomm** [comment]
by the way docker builds only takes the version of feelpp and use it to build the tag. it doesn't care about the version except for special characters not supported in tags such as `+` or `/`

**Comment by gdolle** [comment]
It does not break the pipeline. It breaks the latest tag conversion. The tag is deduced from a regular expression.

**Comment by prudhomm** [comment]
Sure
