### ISSUE TITLE
Update Paraview support to 5.5 or 5.6

### ISSUE THREAD

**Issue by prudhomm** [feelpp/docker#21]
to enable paraview web service we need to have at least paraview 5.5. 
paraview 5.5 fails to compile properly so we should use 5.6 (rc2)

**Comment by Trophime** [comment]
@prudhomm correct the version in feelpp-env/Docker-Paraview line 15.
Actual version is 5.4 should be 5.5!

**Comment by prudhomm** [comment]
@Trophime Docker-paraview is not used in fact, have a look at Docker-paraview-ubuntu-16.04
