### ISSUE TITLE
Remove sources from docker images

### ISSUE THREAD

**Issue by Trophime** [feelpp/docker#24]
Unless I'm working with old images, it seems that the docker images are
still containing srcs. The srcs would eventually be "required" if we were compiling
with Debug/RelWithDebugInfo flag otherwise they are not needed. 

Could we really remove feelpp from /home/feelpp/src after a successful build?
In the case of  feelpp-toolboxes we could save up to 380 MB...

**Comment by prudhomm** [comment]
the source files are removed from docker
