### ISSUE TITLE
Issue with OpenMPI in docker

### ISSUE THREAD

**Issue by prudhomm** [feelpp/docker#26]
when @vincentchabannes run executables in docker, all work well but he has a lot of messages like: 
```
Read -1, expected <someNumber>, errno =1
```
see https://github.com/open-mpi/ompi/issues/4948  for more details.
it solves the problem.

- Solution 1: add an mca parameter to mpiexec launches: 
```
mpiexec -n 4 --mca btl ^vader feelpp_qs_laplacian_2d --checker.solution x**2+y**2 --ksp-monitor=1 --pc-type lu
````
- Solution 2: just `export OMPI_MCA_btl_vader_single_copy_mechanism=none`

Maybe we could add the env variable in feelpp-env?

**Comment by Trophime** [comment]
I would prefer solution 2.
 This also means that the same env var shall be defined singularity recipes I guess

**Comment by prudhomm** [comment]
solution 2 does not work @vincentchabannes

**Comment by prudhomm** [comment]
solution 1 works

**Comment by vincentchabannes** [comment]
@prudhomm you do a mistake when you copy past the solution 2. I fixed it.

**Comment by Trophime** [comment]
@vincent do you have committed the changes? because it seems that docker images for toolboxes on ubuntu 20.04 still has: `ENV OMPI_MCA_btl_btl_vader_single_copy_mechanism=none`
