### ISSUE TITLE
Please replace reference to jfrog depot

### ISSUE THREAD

**Issue by Trophime** [feelpp/docker#33]
Hi,
in latest` feelpp-toolboxes` (same for `feelpp-mor` image) there is still a reference to jfrog depot
This creates an error when building docker on top of this image.

**Comment by prudhomm** [comment]
@Trophime where exactly should I look ?

**Comment by Trophime** [comment]
feelpp-toolboxes/Dockerfile-buster
feelpp-mor/Dockerfile-buster

**Comment by prudhomm** [comment]
we cannot support buster anymore. we now support bullseye, is that ok for you ?

**Comment by Trophime** [comment]
It's ok for me.
You can close the issue.
