### ISSUE TITLE
Install h5py package

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/docker#34]
This package is useful to save and load basis at format `h5` (see https://github.com/feelpp/feelpp/pull/1787/commits/a217ecabedd59e95350a0c6baf4376d87a54293a for where it is used in pyfeelpp).
The package can be installed using `pip install h5py` (see [Pypi](https://pypi.org/project/h5py/), or [the documentation](https://docs.h5py.org/en/latest/index.html))

**Comment by prudhomm** [comment]
pip should not be used unless the package is not found in ubuntu
