### ISSUE TITLE
feelpp packages missing from bullseye docker image

### ISSUE THREAD

**Issue by Trophime** [feelpp/docker#49]
@prudhomm  In latest build for Bullseye image see [log](https://github.com/feelpp/docker/actions/runs/3407906262/jobs/5667985049
there are no feelpp package:)

```
#9 5.936 E: Failed to fetch http://apt.feelpp.org//bullseye/dists/bullseye/InRelease  403  Forbidden [IP: 52.95.156.84 80]
#9 5.936 E: The repository 'http://apt.feelpp.org//bullseye bullseye InRelease' is not signed.
#9 5.948 Reading package lists...
#9 6.370 Building dependency tree...
#9 6.464 Reading state information...
#9 6.568 E: Unable to locate package feelpp-*
#9 6.568 E: Couldn't find any package by glob 'feelpp-*'
#9 6.568 E: Couldn't find any package by regex 'feelpp-*'
#9 6.568 E: Unable to locate package libfeelpp1
#9 6.568 E: Unable to locate package python3-feelpp*
#9 6.568 E: Couldn't find any package by glob 'python3-feelpp*'
#9 6.568 E: Couldn't find any package by regex 'python3-feelpp*'
#9 DONE 6.6s
```

This is due to a missing FLAVOR var in the github action matrix.
see https://github.com/feelpp/docker/actions/runs/3407906262/jobs/5667985049#step:6:109

Same also apply to sid image.
But not with testing
see https://github.com/feelpp/docker/actions/runs/3407654948/jobs/5667688575#step:6:109

**Comment by Trophime** [comment]
@prudhomm manualy run workflows are ok but not those run automatically (eg feelpp Docker #145: Repository dispatch triggered by [prudhomm](https://github.com/prudhomm). See the buildx command lines in the logs

For manualy run workflow, the matrix operation is executed prior to the "buildx". For automatic workflow, "buildx" is made before matrix def. Dunno if it helps to fix this

**Comment by Trophime** [comment]
In https://github.com/feelpp/docker/blob/84f57abd1f8944dc9b4d42e40bca426d2a3cc6ac/.github/workflows/feelpp-docker.yml#L39-L48
    
    The include section should had a flavor entry no?

**Comment by prudhomm** [comment]
this is fixed

**Comment by prudhomm** [comment]
The feelpp builds do not propagate the flavor. Hence the issue.
