### ISSUE TITLE
Correct python path to library for latest dev version

### ISSUE THREAD

**Issue by Trophime** [feelpp/docker#7]
https://github.com/feelpp/docker/blob/ee221a894e71234ea471559ef96e653823f34351/feelpp-base/feelpp.conf.sh#L19

For latest version of feelpp I guess that this line should refer to python3.5 and no longer to python2.7?

**Comment by prudhomm** [comment]
good catch, thanks. However it does not seem to be a problem so far.
It needs to be cleaned up though

**Comment by prudhomm** [comment]
this has been fixed
